databases:
  - name: marvel
    databaseName: marvel
    user: marvel

services:
  - type: web
    name: marvel
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn django_marvel.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marvel
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4